# Generated by Django 2.1.7 on 2019-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('Client', 'Client'), ('Consultant', 'Consultant')], default='Client', max_length=20),
        ),
    ]
