# Generated by Django 2.1.7 on 2019-05-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In progres', 'In progres'), ('Done', 'Done')], default='Todo', max_length=10)),
                ('closed', models.DateField(blank=True, null=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('thread', models.CharField(default='', max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('priority', models.IntegerField(default=1)),
                ('test', models.CharField(default='test', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.Category')),
            ],
        ),
    ]
